export const AppTheme = {
  colors: {
    background: '#F2F8F8',
    surface: '#FFFFFF',
    card: '#FFFFFFF0',
    glass: '#FFFFFFCC',
    primary: '#0FA39A',
    primaryDark: '#0A6E68',
    accent: '#FFB547',
    accentSoft: '#FFE3B7',
    text: '#12312E',
    textSoft: '#4B6864',
    border: '#D5E8E4',
    danger: '#D15454',
    heroA: '#D6F5F0',
    heroB: '#F8FDEB',
    heroC: '#E8F3FF',
    heroD: '#FDEFD9',
    imageOverlay: '#091B1A66',
    imageOverlayStrong: '#091B1AB3',
  },
  radius: {
    md: 12,
    lg: 18,
    xl: 24,
  },
  shadow: {
    card: {
      shadowColor: '#0B3F36',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 22,
      elevation: 4,
    },
    soft: {
      shadowColor: '#0B3F36',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.07,
      shadowRadius: 14,
      elevation: 2,
    },
  },
};
