export const AppTheme = {
  colors: {
    background: '#F3ECE3',
    surface: '#FFFFFF',
    surfaceSoft: '#FCFAF6',
    surfaceElevated: '#FFFFFFFA',
    card: '#FFFFFFF2',
    glass: '#FFFFFFE8',
    mutedBg: '#F6EFE4',
    primary: '#F6A83C',
    primaryDark: '#E38E16',
    accent: '#111111',
    accentSoft: '#FCE6C4',
    text: '#121212',
    textMuted: '#877D70',
    textSoft: '#746D63',
    border: '#EAE0D3',
    borderStrong: '#E4D7C3',
    successSoft: '#EDF7EE',
    danger: '#D15454',
    heroA: '#F7EFE5',
    heroB: '#F3E8DB',
    heroC: '#EFE4D6',
    heroD: '#F9F2E8',
    imageOverlay: '#1A130B55',
    imageOverlayStrong: '#1A130BB3',
  },
  radius: {
    md: 12,
    lg: 18,
    xl: 24,
  },
  shadow: {
    card: {
      shadowColor: '#2B2014',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 20,
      elevation: 4,
    },
    soft: {
      shadowColor: '#2B2014',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
  },
};
